api:
  - changed-files:
      - any-glob-to-any-file: packages/api/**/*

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - packages/api/README.md
          - "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file: pnpm-lock.yaml

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
